name: Node CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, lts, latest]
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: yarn install
      - run: yarn run ci

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install -g yarn
  #     - run: yarn
  #     - run: yarn build
  #     - run: npx semantic-release@^15
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
