name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [8, 10]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g yarn
    - run: yarn
    - run: yarn ci
    - run: yarn build
    - run: npx semantic-release@^15
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install -g yarn
    - run: yarn
    - run: npx semantic-release

    #steps:
#    - uses: actions/checkout@v1
 #   - name: Use Node.js ${{ matrix.node-version }}
  #    uses: actions/setup-node@v1
   #   with:
    #    node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm install
#        npm run build --if-present
#        npm test
