name: Node CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 13.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Echo versions used
      run: echo "Node:" && node --version && echo "npm:" && npm --version && echo "yarn:" && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Run CI script
      run: yarn run ci

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Echo versions used
      run: echo "Node:" && node --version && echo "npm:" && npm --version && echo "yarn:" && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Run build
      run: yarn run build

    - name: Branch name
      run: echo ${GITHUB_REF:11}

# name: Node CI

# on: [push]

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [8, lts, latest]
#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#       - uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: node --version
#       - run: yarn install
#       - run: yarn run ci
#       - run: echo $CI
#         env:
#           CI: true

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: npm install -g yarn
  #     - run: yarn
  #     - run: yarn build
  #     - run: npx semantic-release@^15
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
